language: java
jdk:
      - oraclejdk7
      - openjdk7
      - openjdk6
      - openjdk5
script:
      - jdk_switcher use oraclejdk7
      - # do stuff with Java 7
      - jdk_switcher use openjdk6
      - # do stuff with Java 6
      - jdk_switcher use openjdk5
      - # do stuff with Java 5